### PR TITLE
Fix router bug

### LINKED ISSUE #15: Fix router bug
The 404 error component is not loading when a user selects an invalid path.

### PR DESCRIPTION
**Pull request by rachelJensen**
### Description
Resolved router issue where the movie detail component was being loaded when there wasn't a matching id (and thus throwing an error)

#### Type of change
- [x] Bug fix
- [ ] New feature
- [ ] New feature that breaks previous code
- [ ] Refactor

#### How Has This Been Tested?
- [x] dev tools
- [x] run local:8080
- [x] console.log()

#### Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

#### Additional Comments:
Closes #15

### CODE REVIEW

File: src/components/App/App.js [hunk 1]
```diff
@@ -49,11 +48,15 @@ class App extends Component {
       <main>
         <Header  reload={this.reload}/> 
         <Switch>
-          <Route exact path='/' render={() => <MoviesContainer movies={this.state.movies} findMovie={this.findMovie} />} />
-          <Route exact path='/:id' render={({ match }) => {
-          return <MovieDetailer movie={this.state.movie} hanldeSingleMovie={this.hanldeSingleMovie} location={match.params.id} />} }/>
-          {/* <Route path='*' exact={true} component={Error404}/> */}
-          {/* <Redirect to='/'/> */}
+          <Route exact path="/">
+            <Redirect to="/movies" />
```
Comment (saberg1) [inline src/components/App/App.js:52]: Nice catch getting the switch working!!
